spring:
  application:
    name: AthleteArena

  data:
    mongodb:
      uri: ${MONGO_URI}

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 8080

jwt:
  secretKey: ${JWT_SECRET}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}


NEWS-API-KEY: ${NEWS_API_KEY}